# -*- coding: utf-8 -*-
"""Listening excercise

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_pLjlLS3cNy2AnQOHXPJFkhFE81bxKCL
"""

#sudo pip install pyttsx

import pyttsx
engine = pyttsx.init()
engine.say('The quick brown fox jumped over the lazy dog.')
engine.runAndWait()


#sudo apt-get install espeak
import os
os.system("espeak 'The quick brown fox'")

